version: "3.8"

services:
  twitter-ai:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reporter
    restart: unless-stopped

    # 环境变量配置
    environment:
      - NODE_ENV=production
      - TZ=Asia/Shanghai

    # 环境变量文件
    env_file:
      - .env

    volumes:
      # 报告输出目录同步
      - ./reports:/app/reports

      # 日志目录同步
      - ./logs:/app/logs

      # 其他重要文件同步
      - ./cookies.json:/app/cookies.json
      - ./.env:/app/.env:ro

    # 网络配置
    networks:
      - twitter-ai-network

    # 资源限制（适配群辉NAS）
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

    # 安全配置
    security_opt:
      - no-new-privileges:true

    # 工作目录
    working_dir: /app

    # 标签
    labels:
      - "com.docker.compose.project=twitter-ai-reporter"
      - "description=Twitter AI智能分析和报告生成系统"

networks:
  twitter-ai-network:
    driver: bridge
    name: twitter-ai-network
