version: '3.8'

services:
  ai-tech-brief:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-tech-brief
    restart: unless-stopped
    ports:
      - "8096:80"
    environment:
      - NODE_ENV=production
      - TZ=Asia/Shanghai
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
    volumes:
      # 挂载日志目录到宿主机
      - ./logs:/app/logs
      # 挂载 outputs 目录到宿主机（映射到前端 public 目录）
      - ./frontend/public/outputs:/app/outputs
      # 挂载环境变量文件（如果存在）
      - ./.env:/app/.env:ro
    networks:
      - ai-tech-brief-network
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M
    security_opt:
      - no-new-privileges:true
    working_dir: /app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.docker.compose.project=ai-tech-brief"
      - "com.docker.compose.service=ai-tech-brief"
      - "traefik.enable=true"
      - "traefik.http.routers.ai-tech-brief.rule=Host(`localhost`)"
      - "traefik.http.services.ai-tech-brief.loadbalancer.server.port=80"

networks:
  ai-tech-brief-network:
    driver: bridge