version: "3.8"

services:
  ai-tech-brief:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-tech-brief-app
    restart: unless-stopped

    # 环境变量配置
    environment:
      - NODE_ENV=production
      - TZ=Asia/Shanghai

    # 环境变量文件
    env_file:
      - .env

    volumes:
      # 项目代码目录挂载（开发模式）
      - .:/app
      
      # 排除node_modules避免冲突
      - /app/node_modules
      
      # 报告输出目录同步
      - ./outputs:/app/outputs

      # 日志目录同步
      - ./logs:/app/logs

    # 网络配置
    networks:
      - ai-tech-brief-network

    # 资源限制（适配群辉NAS）
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

    # 安全配置
    security_opt:
      - no-new-privileges:true

    # 工作目录
    working_dir: /app

    # 标签
    labels:
      - "com.docker.compose.project=ai-tech-brief"
      - "description=AI技术简报生成系统"

networks:
  ai-tech-brief-network:
    driver: bridge
    name: ai-tech-brief-network