version: '3.8'

services:
  # 前端服务 - React 应用
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: ai-tech-brief-frontend
    restart: unless-stopped
    ports:
      - "8096:80"
    volumes:
      # 挂载 outputs 目录用于显示生成的报告
      - /volume1/homes/wubaiqing/重要数据/027-AI:/usr/share/nginx/html/outputs
    networks:
      - ai-tech-brief-network
    depends_on:
      - backend
    labels:
      - "com.docker.compose.project=ai-tech-brief"
      - "com.docker.compose.service=frontend"

  # 后端服务 - Node.js 爬虫服务
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: ai-tech-brief-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - TZ=Asia/Shanghai
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
      - HEADLESS=true
    volumes:
      # 挂载日志目录到宿主机
      - ./logs:/app/logs
      # 挂载 outputs 目录用于生成报告
      - /volume1/homes/wubaiqing/重要数据/027-AI:/app/frontend/public/outputs
      # 挂载环境变量文件（如果存在）
      - ./.env:/app/.env:ro
      # 挂载 cookies.json 文件
      - ./cookies.json:/app/cookies.json:ro
    networks:
      - ai-tech-brief-network
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M
    security_opt:
      - no-new-privileges:true
    working_dir: /app
    labels:
      - "com.docker.compose.project=ai-tech-brief"
      - "com.docker.compose.service=backend"

# volumes:
  # shared-outputs:
  #   driver: local

networks:
  ai-tech-brief-network:
    driver: bridge